<?php

/**
 * @file
 * Hello World module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hello_world_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.hello_world':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This is an example module.') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
// function  hello_world_webform_submission_svyazatsya_s_nami_add_form__2_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//     // Perform alterations.
//     $form['#submit'][] = 'лолд';
// }

// function hello_world_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//   if ($form_id === 'webform_submission_svyazatsya_s_nami_node_1_add_form') {
//         $form['actions']['submit']['#value'] = 'h345345';
//   }
// }


/**
 * Implements hook_mail().
 */
function hello_world_mail($key, &$message, $params)
{
    switch ($key) {
        case 'hello_world_log':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('There is an error on your website');
            $message['body'][] = $params['message'];
            $user_message = 'The user that was logged in: [current-user:name].';
            $message['body'][] = \Drupal::token()->replace($user_message, ['current-user' => \Drupal::currentUser()]);

            break;
    }
}

