hello_world.settings:
  type: config_object
  label: 'Hello World settings'
  mapping:
    mail:
      type: string
      label: 'Email address for notifications'
hello_world.custom_salutation:
  type: config_object
  label: 'Salutation settings'
  mapping:
   salutation:
     type: string
     label: 'The salutation message'